In [10]:
!pip install pandas scikit-learn gensim


[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: C:\Users\ewfpy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [12]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

In [2]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'bow_tfidf_word2vec.ipynb', 'Tweets.csv']


In [1]:
import pandas as pd

df = pd.read_csv("Tweets.csv")

df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)


In [2]:
text_data = df["text"]
text_data.head()

0                  @VirginAmerica What @dhepburn said.
1    @VirginAmerica plus you've added commercials t...
2    @VirginAmerica I didn't today... Must mean I n...
3    @VirginAmerica it's really aggressive to blast...
4    @VirginAmerica and it's a really big bad thing...
Name: text, dtype: object

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(text_data)

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("Bag of Words Matrix:")
print(X.toarray())

Vocabulary:
['00' '000' '000114' ... 'zv6cfpohl5' 'zvfmxnuelj' 'zzps5ywve2']
Bag of Words Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
import numpy as np

bow_matrix = X.toarray()

normalized_bow = bow_matrix / bow_matrix.sum(axis=1, keepdims=True)

print("Normalized Bag of Words:")
print(normalized_bow)

Normalized Bag of Words:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(text_data)

print("TF-IDF Features:")
print(tfidf.get_feature_names_out())

print("TF-IDF Matrix:")
print(X_tfidf.toarray())

TF-IDF Features:
['00' '000' '000114' ... 'zv6cfpohl5' 'zvfmxnuelj' 'zzps5ywve2']
TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
from gensim.models import Word2Vec

sentences = [text.split() for text in text_data]

model = Word2Vec(sentences, vector_size=50, window=3, min_count=1)

print("Word vector example:")
print(model.wv[model.wv.index_to_key[0]])

Word vector example:
[ 0.1608961   1.2754389   1.4431489   0.8242911  -0.7841847  -1.4393755
  1.6736279   3.1420374  -1.173158   -1.5231843   1.3580655  -1.321197
  0.24065419  1.5281779  -0.66186196  0.2802544   2.9830973  -0.40949973
 -1.8836236  -2.2075748   1.1043473  -0.26043245  3.1379285  -0.25115356
  1.7478801   0.10363759  0.16340524  2.6553094  -1.0633899  -0.15433669
 -0.7409525  -0.35405484  1.1732779  -0.48343128 -0.5796164   0.38487712
  0.7174523  -0.5138556  -0.6324544  -1.3412176   0.4791769  -0.02983121
  0.0730499  -0.36039641  1.339111   -0.06038166 -0.67240345 -0.87174034
  0.81234777  2.807263  ]
